version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
      nodejs: 16
      golang: 1.17
    commands:
      - echo Installing Python dependencies...
      - pip install -r user-service/requirements.txt
      - echo Installing Node.js dependencies...
      - npm install --prefix order-service
      - echo Downloading Go modules...
      - cd payment-service && go mod download && cd ..

  build:
    commands:
      - echo Running Python tests...
      - cd user-service && pytest && cd ..
      - echo Running Node.js tests...
      - npm test --prefix order-service
      - echo Running Go tests...
      - cd payment-service && go test ./... && cd ..

