version: 0.2
phases:
  install:
    commands:
      - pip install -r user-service/requirements.txt
      - npm install --prefix order-service
      - go mod download --directory payment-service
  build:
    commands:
      - pytest user-service
      - npm test --prefix order-service
      - go test ./... --directory payment-service
